const MAPS = {
  GET_CURRENT_CITY_LOAD: 'GET_CURRENT_CITY_LOAD',
  GET_CURRENT_CITY_RES: 'GET_CURRENT_CITY_RES',
  GET_CURRENT_CITY_ERR: 'GET_CURRENT_CITY_ERR',
  GET_SEARCH_CITY_LOAD: 'GET_SEARCH_CITY_LOAD',
  GET_SEARCH_CITY_RES: 'GET_SEARCH_CITY_RES',
  GET_SEARCH_CITY_ERR: 'GET_SEARCH_CITY_ERR',
  SET_CITIES: 'SET_CITIES',
  REMOVE_CITY: 'REMOVE_CITY'
}

export default {
  ...MAPS
}
